@startuml
'https://plantuml.com/sequence-diagram

autonumber

user as "User" ->browser: open
browser as "Browser" -> eService: access webapp
eService -> server as "eID Server": start session
eService <-- server: return session identifier
note right: session id
eService -> eService: generate tcTokenURL
eService -> widget as "UseID Web-Widget": integrate and send tcTokenURL
note left: tcTokenURL
widget -> backend as "UseID Backend Server": get widget with QR Code
note left: tcTokenURL
backend -> backend: generate QR Code
note left: eIDClientURL
widget <-- backend: return widget
eService <-- widget:
browser <-- eService:
user -> smartphone as "Smartphone": open camera
smartphone -> widget: scan QR Code
smartphone <-- widget: return URL to eID Client
note left: eIDClientURL
smartphone -> app as "UseID Mobile App (eID Client)": open
note left: tcTokenURL
app -> eService: get tcToken from tcTokenURL
app <-- eService: return tcToken
note right: tcToken
app -> server: establish connection
app <-- server: return list of requested data
note left: list of requested data
user <-- app: display requested data
user -> app: approve data request
app -> smartphone: access NFT reader
smartphone -> id as "ID card": scan NFT chip
smartphone <-- id: return encrypted identity data
note right: encrypted identity data
app -> server: send encrypted identity data
note right: encrypted identity data
app <-- server: return success


@enduml