name: Generate Exports
on: push

jobs:
  generate-and-commit:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: cd diagrams && npm ci
    - name: Delete existing images
      run: rm -rf diagrams/imgs
    - name: Generate images
      run: cd diagrams && npm run generate-images
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        add: 'diagrams/imgs'
        message: 'Updating diagram exports'
